### ISSUE TITLE
 localization

### ISSUE THREAD

**Issue by alixdehghani** [femioladeji/License-Plate-Recognition-Nigerian-vehicles#32]
I have an issue with localization package that you used in line:
 `label_image = measure.label(localization.binary_car_image)` 
then i get this Error:

`> Traceback (most recent call last):
>   File "medium2.py", line 31, in <module>
>     label_image = measure.label(localization.binary_car_image)
> AttributeError: module 'localization' has no attribute 'binary_car_image'`

what's your solution?
thanks

**Comment by femioladeji** [comment]
That's weird @alixdehghani. When you executed the `localization.py` file did it work?

**Comment by alucard079** [comment]
@alixdehghani @femioladeji 
I'm currently looking in your blog. I have done installing the dependencies. I'm now with the localization.py step and downloading the car.jpg and in the directory of /home/nigel/license-plate-recognition, where should I create the localization.py?

Do I have to clone it first the full project?

Please help me, thanks!

**Comment by alixdehghani** [comment]
I remove `import localization ` and all dependencies then it work correctly.

**Comment by nisyjohn** [comment]
I am also getting the following error:

AttributeError: module 'localization' has no attribute 'binary_car_image'

Could anyone help in resolving this? Any suggestions?

**Comment by Vishnukvsvk** [comment]
I am too getting same error.
Someone please give a solution to this,

**Comment by EvyW** [comment]
Just don't import "location", or comment it, like this:
> # localization
And then remove also "localization in your code so that it looks like this:
> label_image = measure.label(binary_car_image)
> fig, (ax1) = plt.subplots(1)
> ax1.imshow(gray_car_image, cmap="gray");

Then it will be ready and will show you the image of the car with a red square around the license plate :)

**Comment by IVleina** [comment]
Thank you!!
