### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by alucard079** [femioladeji/License-Plate-Recognition-Nigerian-vehicles#33]
I'm currently looking in your blog. I have done installing the dependencies. I'm now with the `localization.py` step and downloading the `car.jpg` and in the directory of `/home/nigel/license-plate-recognition`, where should I create the `localization.py`? 

Do I have to clone it first the full project?

Please help me, thanks!

**Comment by femioladeji** [comment]
You don't need to clone the full project @alucard079.
However there are some things I couldn't implement in the blog post so the full project is more comprehensive. You can use the blog post to understand the thought process and how you can make some adjustments that will fit your use case
