### ISSUE TITLE
No image to display

### ISSUE THREAD

**Issue by Pratipkhandelwal** [femioladeji/License-Plate-Recognition-Nigerian-vehicles#35]
I ran the command python ALPR.py and the gui window appears but there it says no image to display . In the top left it says, File Path : No Image File Chosen .
The test image output should be shown i guess why it is not visible , any leads on it .

Any help would be great 
Thanks .

**Comment by femioladeji** [comment]
No image shows by default. Check your system taskbar. There is a menu where you can choose the image you want to perform ALPR on. Once you select the image then it will show on the app

**Comment by Pratipkhandelwal** [comment]
File "D:\License Plate recog\License\License-Plate-Recognition-Nigerian-vehicles-master\full.py", line 69, in execute_ALPR
    os.path.join(models_folder, 'SVC_model', 'SVC_model.pkl'),(20, 20))
  File "D:\License Plate recog\License\License-Plate-Recognition-Nigerian-vehicles-master\deepMachine.py", line 16, in learn
    return self.classify_objects(objects_to_classify, model, tuple_size)
  File "D:\License Plate recog\License\License-Plate-Recognition-Nigerian-vehicles-master\deepMachine.py", line 33, in classify_objects
    result_index = self.letters.index(result[0])
ValueError: b'E' is not in list


I have uploaded the image and then used RUN ALPR but the above error is coming in the prompt ....How to resolve it ?

**Comment by femioladeji** [comment]
I'm guessing you're running python 3. Check this out on how to resolve it https://stackoverflow.com/questions/37016946/remove-b-character-do-in-front-of-a-string-literal-in-python-3
