### ISSUE TITLE
cannot recognize test image.

### ISSUE THREAD

**Issue by neverlog** [femioladeji/License-Plate-Recognition-Nigerian-vehicles#36]
When try to test your code with your test image, I get below error:
  
File "D:\carplate\License-Plate-Recognition-Nigerian-vehicles-master\deepMachine.py", line 33, in classify_objects
    result_index = self.letters.index(result[0])
ValueError: b'E' is not in list

**Comment by femioladeji** [comment]
Hi @neverlog I think it has to do with string encoding in python 3, it’s possible the string was converted to bytes. You may need to call a .decode() method. Check out this stackoverflow question https://stackoverflow.com/questions/37016946/remove-b-character-do-in-front-of-a-string-literal-in-python-3

**Comment by anil-ajax** [comment]
Not sure how to use the code given in solution. Can you share updated lines in deepmachine.py
