### ISSUE TITLE
module 'localization' has no attribute 'binary_car_image'

### ISSUE THREAD

**Issue by Vishnukvsvk** [femioladeji/License-Plate-Recognition-Nigerian-vehicles#39]
from skimage import measure
from skimage.measure import regionprops
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import localization

# this gets all the connected regions and groups them together
label_image = measure.label(localization.binary_car_image)

fig, (ax1) = plt.subplots(1)
ax1.imshow(localization.gray_car_image, cmap="gray");

# regionprops creates a list of properties of all the labelled regions
for region in regionprops(label_image):
    if region.area < 50:
        #if the region is so small then it's likely not a license plate
        continue

    # the bounding box coordinates
    minRow, minCol, maxRow, maxCol = region.bbox
    rectBorder = patches.Rectangle((minCol, minRow), maxCol-minCol, maxRow-minRow, edgecolor="red", linewidth=2, fill=False)
    ax1.add_patch(rectBorder)
    # let's draw a red rectangle over those regions

plt.show()

AttributeError                            Traceback (most recent call last)
<ipython-input-29-d6be5058e782> in <module>()
      6 
      7 # this gets all the connected regions and groups them together
----> 8 label_image = measure.label(localization.binary_car_image)
      9 
     10 fig, (ax1) = plt.subplots(1)

AttributeError: module 'localization' has no attribute 'binary_car_image'

**Comment by femioladeji** [comment]
@Vishnukvsvk did you ensure the localization.py file has been run before running this file

**Comment by JigarJoshi04** [comment]
just use binary_car_image insted of using localization.binary_car_image

**Comment by JigarJoshi04** [comment]
Ensure that you run localization.py file before running this main file

**Comment by Vishnukvsvk** [comment]
> just use binary_car_image insted of using localization.binary_car_image

Thanks. This helped me.
