### ISSUE TITLE
NON-USE OF GUI

### ISSUE THREAD

**Issue by Skyeprince** [femioladeji/License-Plate-Recognition-Nigerian-vehicles#40]
Good day Mr. Femi

Please is it possible to run this code without the use of gui? I am talking of something like when I run the full.py, program, there is already a path for the image and it automatically shows me the license plate text already extracted instead of running the gui and pressing 'RUN ALPR' all the time

I'll be expecting a response.

**Comment by femioladeji** [comment]
@Skyeprince I think if you replace the `imagePath` variable in `full.py` and you make some modifications to the file so that the `execute_ALPR` function runs it should work. It has been a while I worked on this so I'm not 100% sure. I think going through the medium article will also help you a lot
