### ISSUE TITLE
After Installation GUI do not work at all 

### ISSUE THREAD

**Issue by bhargavravat** [femioladeji/License-Plate-Recognition-Nigerian-vehicles#41]
@femioladeji  : I have done installation based on your README file and everything is nicely installed. Now the moement I try to run ALPR.py file it is not allowing me to access any of the functionality of GUI. I am trying to give image file as input using GUI , however unable to do so. 

**Attached is the screen shot for your information. Would be really happy if you can help me out with this. ** 

![image](https://user-images.githubusercontent.com/11025174/84987692-46bc2900-b15e-11ea-9060-61500198cfaa.png)

**Comment by femioladeji** [comment]
@bhargavravat when you select the GUI can you check your system's menubar. I can see that you're using Linux and I had the issue also in the past. You can check this https://stackoverflow.com/questions/5023255/wxpython-menu-bar-not-displaying#:~:text=Someone%20had%20a%20similar%20issue,it%20has%20the%20same%20issue.

**Comment by femioladeji** [comment]
@bhargavravat have you been able to fix this?
